- hosts: srv
  roles:
  - role: guifibages_server

- hosts: airvision
  roles:
  - role: airvision

- hosts: [sllajuntament, guifiserver]
  roles:
  - role: guifi

- hosts: eurocopter
  roles:
  - role: guifibages_docker
