---
- name: Common packages
  apt: name={{item}} state=present
  with_items:
    - rsyslog
    - vim
    - less
    - iputils-ping
    - screen
    - sudo
    - libnss-ldap
    - libpam-ldap
    - ca-certificates
    - cpio
    - bash-completion
    - traceroute
    - fail2ban
    - nscd

- name: Ensure nscd is running
  service: name=nscd state=started

- name: Common files
  copy: src={{item}} dest=/{{item}} owner=root group=root mode=0644
  with_items:
    - etc/resolv.conf
    - etc/nsswitch.conf
    - etc/ldap/ldap.conf
    - etc/pam.d/common-session
    - etc/profile.d/guifibages.sh

- name: Remove /etc/motd.tail
  file: path=/etc/motd.tail state=absent

- name: Common templated files
  template: src={{item}}.j2 dest=/etc/{{item}}
  with_items:
    - motd
    - pam_ldap.conf
    - libnss-ldap.conf
