---
- name: ensure docker-py is present
  pip: name=docker-py

- name: docker containers
  docker:
    name: "{{item.name}}"
    image: "{{item.image}}"
    ports: "{{item.ports}}"
    links: "{{item.links}}"
    state: started
    volumes: "{{item.volumes}}"
    command: "{{item.command}}"
  when: docker_containers is defined
  with_items: docker_containers
  tags: docker