---
- name: rewrite squid config
  command: /usr/share/guifi-proxy3/guifi-proxy3.sh
  notify: check squid

- name: check squid
  command: /usr/share/guifi-proxy3/check_squid.sh

- name: Update CA certificates
  command: /usr/sbin/update-ca-certificates
